### ISSUE TITLE
export list of files to exclude from final extraction

### ISSUE THREAD

**Issue by bdietz** [bulk-reviewer/bulk-reviewer#16]
Based on a BR review, I would like to be able to export a list of paths to files containing PII that I want to exclude from a final package (TAR), so that I could use it as, or to create, an "exclude" file to be used in a tar command.

**Comment by tw4l** [comment]
Thanks for the suggestion! Is there a particular format for the list (beyond just a list of strings, with each being a path to a file to exclude) that would be most helpful to you? Would you want to run the tar command, including the excludes, as an export type directly from Bulk Reviewer?

**Comment by bdietz** [comment]
I think just the strings. If you could escape special characters in those strings, that would be ideal, although TAR seems to work without escaped characters in the exclude file. A user can perform that escaping on their own with a handy cheat sheet and a faithful F+R. I think the risk of baking the actual TARing functionality into BR is that a user might not be able to run the desired command.

**Comment by tw4l** [comment]
Hi Brian. This feature is implemented in Bulk Reviewer 0.2.0 (released today). In this version the strings are written utf-8 encoded, without escaping characters. If that proves to be an issue in practice let me know/re-open this issue and I'll add character escaping into the next patch release. Thanks again for your really helpful feedback!
