### ISSUE TITLE
Include lightgrep scanner results in "User-supplied regular expressions"

### ISSUE THREAD

**Issue by hannahlwang** [bulk-reviewer/bulk-reviewer#19]
Based on my review of BR, I would like to have results from the lightgrep scanner included in the “User-supplied regular expressions” filter in the Review Dashboard, which is currently limited to the results of the find scanner. It might also make sense to deduplicate these results, since the results of both scanners (if both are run) will be redundant.

**Comment by tw4l** [comment]
Thank you, Hannah, and good timing! In Bulk Reviewer 0.2.0 (out today), features in both `lightgrep.txt` and `find.txt` map to "User-supplied regular expressions". If BR finds both `lightgrep.txt` and `find.txt` in the feature files directory, it will read only from `lightgrep.txt`, which should get rid of the duplicate results.
