### ISSUE TITLE
wget in README code blocks grabs github DOM instead of shell scripts

### ISSUE THREAD

**Issue by markpbaggett** [bulk-reviewer/bulk-reviewer#22]
Hello, 

For some reason, wget commands in the code blocks in the README try to download the GitHub DOM rather than the actual shell script.  This seems to be the case with wget on OS X and Ubuntu 18.04. Oddly, curl doesn't have this problem. Regardless, pointing at the raw file with wget downloads the shell script as expected.

I opened a [pull request](https://github.com/bulk-reviewer/bulk-reviewer/pull/21) for this (if it's wanted) but feel free to close if you want to go about addressing this another way.

**Comment by tw4l** [comment]
PR merged
