### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by mpeachy** [bulk-reviewer/bulk-reviewer#29]
I'm encountering an encoding error in the br_processor.py code (see attached screenshot) when trying to run BR over a directory containing pdf and doc(x) files. This is preventing proper use of the application to interpret BE reports.

<img width="240" alt="encoding error" src="https://user-images.githubusercontent.com/16196574/92518062-c4378880-f1e5-11ea-8906-4ff12fed8252.png">

**Comment by tw4l** [comment]
Hi @mpeachy - thanks for the bug report! And sorry for the slow reply - this got a bit lost in my inbox.

My hunch is that this is happening when reading bulk_extractor feature files that were created in Windows. Is that true?

I think the fix for this shouldn't be too complicated - I'll try to get a patch out shortly.

**Comment by tw4l** [comment]
@mpeachy It would be helpful to know what character encoding the files are in (there are a few possibilities for Windows).

Would you be willing to check the character encoding of these feature files using [chardet](https://github.com/chardet/chardet)? You should be able to do that with:

```
pip install chardet
chardetect /path/to/file
```

Notepad++ is also pretty good at detecting character encodings if that's an easier option for you (the character encoding is displayed on the bottom right of the window, in the Notepad++ footer, after opening a file).

Of course you could also just share the file directly with me, but I'm assuming some of the content is sensitive, in which case one of the above methods is probably better.

Thank you!

**Comment by mpeachy** [comment]
@tw4l I encountered the error in an Ubuntu VM on a Windows machine. The files have ANSI encoding (according to Notepad++ - running chardetect returns 'no result'.

**Comment by tw4l** [comment]
Thanks @mpeachy. I've put together a release candidate for Bulk Reviewer 0.2.1 with a bug fix: https://github.com/bulk-reviewer/bulk-reviewer/releases/tag/v0.2.1-rc1.

Would you mind trying out the 0.2.1 AppImage in your Ubuntu VM when you get a chance to see if that resolves the issue?

**Comment by mpeachy** [comment]
Thank you @tw4l - I had success with 0.2.1!

**Comment by tw4l** [comment]
@mpeachy Excellent, glad to hear it. I just published the release properly: https://github.com/bulk-reviewer/bulk-reviewer/releases/tag/v0.2.1. Thanks again for the bug report and your patience with the fix!
